# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 597f53e5a07138f082bbf8ce3d1f42e96f564e287f98fd24cf8a8077305ba670e8057f893f7208c0039833b6f1d9911ec86ba8ef1f5817eda1947367a6bc4123

test:
  secret_key_base: 26ff4359757ac6c89373f56903b6d67b54eff7020031d2a3d122418044f89d3095a17211bedc969406bac09700c55543ab44852ac3e0c8029af9433a45aac1ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
